Repository TOBE-TOGETHER/tobe-blog, pull requests merged in 2024-06, with the labels that each got.

#24 Enhance UI style of admin
  tobe_blog_service/src/main/java/com/tobe/blog/beans/consts/Const.java
  tobe_blog_service/src/main/java/com/tobe/blog/beans/dto/content/BaseContentCreationDTO.java
  tobe_blog_service/src/main/java/com/tobe/blog/beans/dto/content/BaseContentDTO.java
  tobe_blog_service/src/main/java/com/tobe/blog/beans/dto/content/BaseContentUpdateDTO.java
  tobe_blog_service/src/main/java/com/tobe/blog/beans/dto/content/BaseSearchFilter.java
  tobe_blog_service/src/main/java/com/tobe/blog/beans/dto/content/CollectionDTO.java
  tobe_blog_service/src/main/java/com/tobe/blog/beans/entity/content/CollectionEntity.java
  tobe_blog_service/src/main/java/com/tobe/blog/beans/entity/content/ContentGeneralInfoEntity.java
  tobe_blog_service/src/main/java/com/tobe/blog/content/controller/IContentController.java
  tobe_blog_service/src/main/java/com/tobe/blog/content/controller/impl/BaseContentController.java
  tobe_blog_service/src/main/resources/com/tobe/blog/content/mapper/BaseContentMapper.xml
  tobe_blog_service/src/test/resources/schema/table.sql
  tobe_blog_web/public/locales/en/translation.json
  tobe_blog_web/public/locales/zh/translation.json
  tobe_blog_web/src/admin/components/header/BackendHeader.tsx
  tobe_blog_web/src/admin/components/layout/BackendLayout.tsx
  tobe_blog_web/src/admin/components/misc/CardHeaderActionButton.tsx
  tobe_blog_web/src/admin/components/misc/InfiniteScrollList.tsx
  tobe_blog_web/src/admin/components/navigator/NavItems.tsx
  tobe_blog_web/src/admin/components/navigator/SideNav.tsx
  tobe_blog_web/src/admin/components/table/PagedTable.tsx
  tobe_blog_web/src/admin/containers/analytics/AnalyticsPage.tsx
  tobe_blog_web/src/admin/containers/content/article/ArticleCreationPage.tsx
  tobe_blog_web/src/admin/containers/content/article/ArticleDetailPage.tsx
  tobe_blog_web/src/admin/containers/content/article/components/ArticleEditMainSection.tsx
  tobe_blog_web/src/admin/containers/content/collection/CollectionCreationPage.tsx
  tobe_blog_web/src/admin/containers/content/collection/CollectionDetailPage.tsx
  tobe_blog_web/src/admin/containers/content/collection/CollectionsPage.tsx
  tobe_blog_web/src/admin/containers/content/components/GeneralCard.tsx
  tobe_blog_web/src/admin/containers/content/components/GeneralCardView.tsx
  tobe_blog_web/src/admin/containers/content/components/GeneralContentListPage.tsx
  tobe_blog_web/src/admin/containers/content/components/GeneralContentListPageFunctionBar.tsx
  tobe_blog_web/src/admin/containers/content/plan/PlanCreationPage.tsx
  tobe_blog_web/src/admin/containers/content/plan/PlanDetailPage.tsx
  tobe_blog_web/src/admin/containers/content/plan/PlansPage.tsx
  tobe_blog_web/src/admin/containers/content/plan/component/PlanProgressItem.tsx
  tobe_blog_web/src/admin/containers/content/plan/component/PlanProgressModal.tsx
  tobe_blog_web/src/admin/containers/content/vocabulary/VOCCreationPage.tsx
  tobe_blog_web/src/admin/containers/content/vocabulary/VOCDetailPage.tsx
  tobe_blog_web/src/admin/containers/profileSettingPage/AvatarSelector.tsx
  tobe_blog_web/src/admin/containers/profileSettingPage/ProfileSettingPage.tsx
  tobe_blog_web/src/commons/TimeFormat.ts
  tobe_blog_web/src/components/layout/Page.tsx
  tobe_blog_web/src/components/layout/SidePanel.tsx
  tobe_blog_web/src/global/types.ts
  tobe_blog_web/src/portal/components/FrontendLayout.tsx
  tobe_blog_web/src/portal/components/HeaderLanguageMenu.tsx
  tobe_blog_web/src/portal/containers/home/FeaturedNews.tsx
  tobe_blog_web/src/portal/containers/home/FunctionSection.tsx
  tobe_blog_web/src/portal/containers/home/GreatingSection.tsx
  tobe_blog_web/src/portal/containers/home/TagStatisticsFilterPanel.tsx
  tobe_blog_web/src/portal/containers/signIn/SignIn.tsx
  tobe_blog_web/src/portal/containers/signUp/SignUp.tsx
  tobe_blog_web/src/services/DomainService.ts
  tobe_blog_web/src/theme.ts
Labels: 🖥️ SERVER, 🕸️ WEB

#25 feat(article): update the articles
  tobe_blog_web/src/commons/index.ts
  tobe_blog_web/src/components/common/TagDisplayBar.tsx
  tobe_blog_web/src/components/index.ts
  tobe_blog_web/src/global/enums.ts
  tobe_blog_web/src/global/types.ts
  tobe_blog_web/src/portal/PortalRoutes.tsx
  tobe_blog_web/src/portal/URL.ts
  tobe_blog_web/src/portal/components/AuthorDisplayPanel.tsx
  tobe_blog_web/src/portal/components/Breadcrumbs.tsx
  tobe_blog_web/src/portal/components/ContentPageBreadcrumbsBar.tsx
  tobe_blog_web/src/portal/components/ContentPageFrame.tsx
  tobe_blog_web/src/portal/components/ContentPageMetaBar.tsx
  tobe_blog_web/src/portal/components/RelevantContentPanel.tsx
  tobe_blog_web/src/portal/components/RichContentReader.tsx
  tobe_blog_web/src/portal/components/index.ts
  tobe_blog_web/src/portal/containers/domain/article/ArticleReadingPage.tsx
  tobe_blog_web/src/routes/MainRouter.tsx
Labels: :sparkles: feature

#28 feat(icon): create a stroke animation component
  tobe_blog_web/src/components/common/StrokeText.tsx
  tobe_blog_web/src/portal/components/HeaderUserMenu.tsx
  tobe_blog_web/src/portal/components/PortalHeader.tsx
Labels: :sparkles: feature, :lipstick: style
